spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-auth
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - AuthenticationFilter

        - id: enrollment-service
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/api/v1/enrollments/**
            - Path=/api/v1/payments/**
            - Path=/api/v1/learning-progress/**
          filters:
            - AuthenticationFilter

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
