apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eduflow-ingress
  namespace: eduflow
spec:
  rules:
    - host: eduflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 80
