apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-enrollment
  namespace: eduflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-enrollment
  template:
    metadata:
      labels:
        app: postgres-enrollment
    spec:
      containers:
      - name: postgres-enrollment
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: enrollment_db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: eduflow-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eduflow-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-enrollment-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-enrollment-storage
        persistentVolumeClaim:
          claimName: postgres-enrollment-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-enrollment-service
  namespace: eduflow
spec:
  selector:
    app: postgres-enrollment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
