apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: ghcr.io/${GITHUB_REPOSITORY}/course-service:latest
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: eduflow-config
        - secretRef:
            name: eduflow-secrets
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
