apiVersion: v1
kind: Secret
metadata:
  name: eduflow-secrets
  namespace: eduflow
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  MONGO_ROOT_USERNAME: cm9vdA==
  MONGO_ROOT_PASSWORD: ZXhhbXBsZQ==
  JWT_SECRET: <BASE64>
